---
title: "EDA Report"
subtitle: "Data Science III" 
author: "Carlyn Savino"
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Overview


Every year, the United Nations Development Programme publishes the Human Development Report. The report combines various statistics such as life expectancy, income, and years of schooling to rank every country according to its overall level of human development. The data was collected directly from the 2016 report (the entirety of which can be found here: http://hdr.undp.org/sites/default/files/2016_human_development_report.pdf). Here is the source of the dataset that will be used for this project:


Kumar, Sudhir (2018): "Human Development Reports." Version 5. Kaggle. https://www.kaggle.com/sudhirnl7/human-development-index-hdi


There are 195 observations in the dataset (one for every country in the world). Technically, every variable in this dataset can potentially be used as a feature (predictor), but for the purposes of this project, I will probably end up using 3 or 4 features (1-2 per research question).


Missingness is quite prevalent in this dataset. There is a total of 2041 missing values across all columns. In general, the easier the statistic is to obtain, the less likely that missing values will be present. For example, there are no missing values in the columns that cover population counts/trends because that data is systematically obtained through measures such as censuses. On the other hand, almost half of the countries are missing data that covers the unemployment rate of youth ages 15-24 who are not in school, which is quite specific and probably harder to obtain information on.


## Essential Findings


There are two main research questions I seek to answer through my project:

1) Can mean years of schooling and life expectancy predict a country's HDI?
2) Can the number of Internet users predict a country's unemployment rate?


The first question is more of an obvious/expected question for this type of data (although maybe the results will end up subverting expectations!). The second question is one people may not think about as much, and it may not have as obvious of an answer.

### Response Variables


To begin, I performed univariate analysis on the first response variable, `HDI.` This is a continuous variable that contains the Human Development Index for every country. According to the UN, the HDI represents a "statistic composite index of life expectancy, education, and per capita income indicators, which are used to rank countries into four tiers of human development." Note that my data does not support being split, since each row represents a country. First, I will report some central tendency measures. Norway has the highest HDI (.949), while Central African Republic has the lowest (.352). The median HDI is approximately .729, while the mean HDI is approximately .699. The minimum and maximum values are quite far away from the median, but there technically are no outliers in the dataset. I used the information provided by `summary()` and calculated the Interquartile Range to determine this. Since there aren't any official outliers for the HDI variable, it does not seem as though there is anything within the `HDI` column itself that will impact model building (except for missing values, which I can omit). In terms of dispersion measures, the range of `HDI` is quite large, at .597 (since this variable is measured on a scale of 0 to 1). The standard deviation is .155.


Next, I performed univariate analysis on the second response variable, `Total Unemployment.` This variable denotes the percentage of the total labor force that was unemployed in 2015. Djibouti had the highest unemployment rate at 53.9, while Qatar had the lowest at 0.2. The median unemployment rate was 7.1, while the mean was 9.336. Next, I performed calculations to determine if there are any outliers. There ended up being 14. To make my models more robust to these outliers, I can use methods such as tree-based modeling and KNN in my final project. Finally, in terms of dispersion measures, the range of the unemployment rate is large, at 53.7. The standard deviation is 7.53.


### Predictor Variables


Now it is time to analyze the predictor variables. First up is `Mean years of schooling.` This variable is self explanatory; it denotes the average number of years that individuals in each country are in school. Switzerland had the highest average, at 13.4 years. Burkina Faso had the lowest, at 1.4 years (which is actually quite astounding). The median was 8.65, while the mean was 8.37. There are no outliers. The range of this variable is 12, and the standard deviation is 3.1.


The next predictor is `Life expectancy.` Hong Kong has the highest life expectancy, at 84.2 years old. Swaziland has the lowest, at just 48.9 years old. This finding is quite remarkable in highlighting the disparities between highly developed and less developed countries. The median life expectancy is 73.3 years old, and the mean is 71.27 years old. There are no outliers. The range of this variable is 35.3 years, and the standard deviation is 8.33.


The last predictor is `Internet users.` This variable measures the percentage of the population that has access to and uses the Internet. Iceland has the highest amount of Internet users, at 98.2. Eritrea has the lowest, with only 1.1 percent of its population using the Internet. This is another eye-opening statistic. The Internet is something so many of us use and take for granted today, but there are many people who lack access to it. The median percentage of Internet users is 47.4, and the mean is 46.93. These values are also actually surprisingly low. There are no outliers. The range of this variable is a whopping 97.1, and the standard deviation is also quite high, at 28.86.


### Response/Predictor Relationships

I first explored the relationship between `HDI` (response variable for my first research question) and `Mean years of schooling` (one of two predictors for my first research question). I created a simple scatterplot to display the relationship between the two variables. Visually, the relationship seemed very strong. I confirmed this by finding the correlation between the two, which ended up being approximately .91. Extremely strong indeed! I expect `Mean years of schooling` to be a pretty powerful predictor when it comes time to build models.


Continuing with my first research question, I explored the relationship between `HDI` and `Life expectancy.` Once again, I created a simple scatterplot to visually depict the relationship, which appeared to be very strong. The official correlation was .9. In conclusion, I expect the models associated with my first research question to perform quite well.


Now, on to my second research question. I explored the relationship between `Unemployment rate` and `Internet users` by creating a scatterplot. Unlike in my first research question, there was not much of a relationship at all. In fact, the variables had a correlation of -.1. The model building process for this model will be more unpredictable and interesting.


### Predictor Relationships

There is only one predictor variable for my second research question, so I explored the relationship between the two predictor variables from my first research question: `Life expectancy` and `Mean years of schooling.` I began by making a scatterplot and fitting a `geom_smooth()` line to the points. It looked like there was some relationship, so I found the correlation, which ended up being about .75. This correlation leans on the stronger side; therefore, I think it's safe to deem multicollinearity a potential issue when building models, but I can use methods such as ridge and lasso regression to help combat this. I also investigated missingness in the two variables. `Mean years of schooling` only had 7 missing values, and `Life expectancy` only had 5. There is no significant chunk of data missing in either variable, which bodes well for model building.


## Secondary Findings


I conducted some additional explorations of variables that I do not currently deem as important to my project. First, I chose to investigate the variable `Share of seats in Parliament held by women.` This variable is a bit unconventional in that I don't think people normally consider it when thinking about a country's development. Also, not all countries have a Parliament. Nonetheless, I performed some basic analyses. There were 4 countries that have no women at all in Parliament: Qatar, Tonga, Micronesia, and Vanuatu. 3 of these countries are in the Oceania region. The country with the most women in Parliament was Rwanda, at 57.5. To be honest, this was a bit unexpected, but I suppose I let stereotypes get in the way of my expectations. I definitely learned something new! Rwanda is an outlier, as confirmed by a boxplot. The median of this variable is 19.4, and the mean is 20.67; both were pretty low.


I also performed explorations of `Mean years of schooling - Male` and `Mean years of schooling - Female.` These variables are in my domain area but are not very important, since I am using the broader `Mean years of schooling` variable in my first research question. Australia had the highest mean years of schooling for females, at 13.4 years. Burkina Faso had the lowest, with only a mean of 1 year of schooling. For males, Germany had the highest, at 13.6 years. Burkina Faso once again had the lowest, at 2 years. The mean for the males data was 8.84 years, while for females it was 8.1. The median for the males was 9 years, while for females it was 8.6. In general, males spend slightly more time in school than females. There are no outliers in either variable. When comparing these two variables to the broader `Mean years of schooling` variable that was explored earlier, there is really nothing surprising. Burkina Faso represented the minimum value for that broad variable as wel; the mean and median were also similar to the ones found in the current analysis. Thus, the findings here are not too interesting or important, but I could see their potential if someone wanted to analyze a country's development solely through a gender-oriented lens.


