---
title: "Data Memo"
subtitle: "Data Science III" 
author: "Carlyn Savino"
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

## Data Source

Every year, the United Nations Development Programme publishes the Human Development Report. The report combines various statistics such as life expectancy, income, and years of schooling to rank every country according to its overall level of human development. I plan on using one of these reports (2016) for my final project. Unfortunately, I was not able to find a more recent report that was formatted in a way conducive to analysis in R (excel, csv, etc.); however, there haven't been massive overhauls in any country's human development during the past few years, so I believe the 2016 report still holds up well. Here is the citation for my dataset:


Kumar, Sudhir (2018): "Human Development Reports." Version 5. Kaggle. https://www.kaggle.com/sudhirnl7/human-development-index-hdi


There are definitely some additional pieces of information that could be useful for this project. I think it would be interesting to create a world map that visually depicts regions that have high/low concentrations of human development. I also think it might be interesting to share findings from the very first HDI report that came out in 1990 and see how much (or how little) things have changed in the past 30 years. Perhaps I could also find an additional dataset regarding global food security and explore relationships between human development and access to food.


## Why This Dataset


I always find the annual Human Development Report quite interesting. The report challenges the idea that economic growth will automatically lead to a country's development; it shows that there are actually many factors that affect development, such as education and access to Internet. What really makes a country developed is not so easy to define.


From a basic inspection, the dataset does not seem to be well suited for classification problems; all of the variables appear to be continuous. Thus, the questions I have in mind so far are regression problems. I am mostly interested in prediction; for example, can public health expenditure and total fertility rate be used to predict HDI rank? Can mean years of schooling be used to predict life expectancy? With 82 different columns, the dataset definitely supports a wide variety of predictive questions.


## Potential Data Issues


After looking through the data, I noticed that missingness is a potential issue. While it seems that most of the columns have data for most of the countries, I will still have to omit some missing values. Also, some of the variables are separated by gender (e.g. "mean years of schooling - female" and "mean years of schooling - male") so I will most likely end up merging these columns to perform a more holistic analysis. Finally, I plan on renaming most of the columns. Most of the column names are extremely specific and involve a mix of words, numbers, and symbols (for example, "Working poor at PPP$3.10 a day (%) 2004-2013") which is not necessarily a bad thing, but for the purposes of model building and working with column names in R, I think it would be best to rework the variable names to be more concise and understandable.

